config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:index, :show, :edit, :update] do
    member do
     get :following, :followers
    end
  end
  root 'top#index'
  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates  :title,         presence: true, length: { maximum: 20 }
  validates  :learning_date, presence: true, uniqueness: { scope: [:user_id] }, length: { is: 8, allow_blank: true }
  validates  :study_time,    presence: true
  validates  :study_minutes, presence: true
  validates  :content,       presence: true
  validates  :study_method,  presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, uniqueness: true, length: { maximum: 8 }

  has_many :posts, dependent: :destroy
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

   # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  add_flash_types :success, :info, :warning, :error

  def set_search
    @search = User.ransack(params[:q])
    @search_users = @search.result
  end

   protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: [:edit, :update, :destroy]
  include PostsHelper

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_path(@post.user_id), success: '投稿しました！'
    else
      flash.now[:error] = '投稿に失敗しました'
      render new_post_path
    end
  end

  def show
    @post = Post.find(id_params[:id])
  end

  def edit
    @post = Post.find(id_params[:id])
  end

  def update
    @post = Post.find(id_params[:id])
    if @post.update(post_params)
      redirect_to "/posts/#{@post.id}", success: '編集しました！'
    else
      flash.now[:error] = '編集に失敗しました'
      render :edit
    end
  end

  def destroy
    post = Post.find(id_params[:id])
    if post.destroy
      redirect_to user_path(post.user_id), success: '投稿を削除しました！'
    else
      flash.now[:error] = '削除に失敗しました'
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :learning_date, :study_time, :content, :study_method, :reflection, :next_study, :other, :study_minutes).merge(user_id: current_user.id)
  end

  def id_params
    params.permit(:id)
  end

  def correct_user
    post  = Post.find(id_params[:id])
    @user = post.user_id
    unless current_user?(@user)
      flash[:error] = "操作が受け付けられません"
      redirect_to(user_path(current_user))
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    relationship =  Relationship.create(create_params)
    redirect_to user_path(id: relationship[:following_id])
  end

  def destroy
    relationship =  Relationship.find(params[:id])
    relationship.destroy
    redirect_to user_path(id: relationship[:following_id])
  end

  private
  def create_params
    params.permit(:following_id).merge(follower_id: current_user.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user               = User.find_by(id: params[:id])
    @posts              = Post.where(user_id: params[:id]).order("learning_date desc")
    study_time_total    = Post.where(user_id: params[:id]).sum(:study_time) * 60
    study_minutes_total = Post.where(user_id: params[:id]).sum(:study_minutes)
    @study_total        = ((study_time_total + study_minutes_total) / 60.to_f).round(1)
    gon.posts           = Post.where(user_id: params[:id])
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id), success: "アカウントを編集しました"
    else
      flash.now[:error] = "編集に失敗しました"
      render :edit
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :avatar_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def current_user?(user)
    user == current_user.id
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
- flash.each do |type, msg|
  :javascript
    toastr.options = {
      "positionClass": "toast-bottom-right"
    }
    toastr['#{type}']('#{msg}');

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title STUDYPOST
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag('/favicon.ico')
    %script{:crossorigin => "anonymous", :integrity => "sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=", :src => "https://code.jquery.com/jquery-3.3.1.js"}
    = include_gon
    = stylesheet_link_tag    'application', href: "https://fonts.googleapis.com/css?family=Fugaz+One", media: 'all'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/_form.html.haml
.form-style
  .form-style-heading 学習記録
  = form_for post do |f|
    %label
      %span
        タイトル
        %span.required *
      = f.text_field :title, type: :text, class: "input input-field", placeholder: "HTML&CSSを中心に学習！"
      - post.errors.full_messages_for(:title).each do |message|
        .post-validation-error-mesage
          = message
    %label
      %span
        学習日
        %span.required *
      = f.number_field :learning_date, class: 'input date-field', placeholder: "20190101(8桁入力)"
      - post.errors.full_messages_for(:learning_date).each do |message|
        .post-validation-error-mesage
          = message
    %label
      %span
        学習時間
        %span.required *
      = f.number_field :study_time, min: 0, max: 23, class: 'input time-field'
      %p.time-space :
      = f.number_field :study_minutes, min: 0, max: 59, class: 'input time-field'
      - post.errors.full_messages_for(:study_time).each do |message|
        .post-validation-error-mesage
          = message
      - post.errors.full_messages_for(:study_minutes).each do |message|
        .post-validation-error-mesage
          = message
    %label
      %span
        学習方法
        %span.required *
      = f.text_area :study_method, type: :text, class: "textarea textarea-field", placeholder: "1時間ごとに学習したことを15分でアウトプットした"
      - post.errors.full_messages_for(:study_method).each do |message|
        .post-validation-error-mesage
          = message
    %label
      %span
        学習内容
        %span.required *
      = f.text_area :content, type: :text, class: "textarea textarea-field", placeholder: "レスポンシブWebデザインの基礎知識、CSSで円を描く方法"
      - post.errors.full_messages_for(:content).each do |message|
        .post-validation-error-mesage
          = message
    %label
      %span
        反省点
      = f.text_area :reflection, type: :text, class: "textarea textarea-field", placeholder: "集中力が続かず、手が止まっていることがあったため、次回からは長時間学習する時は休憩をこまめに取りたい"
    %label
      %span
        次回学習内容
      = f.text_area :next_study, type: :text, class: "textarea textarea-field", placeholder: "レスポンシブWebデザインを対応させる、CSSで中央寄せする方法"
    %label
      %span
        その他
      = f.text_area :other, type: :text, class: "textarea textarea-field", placeholder: "あと少しでWebサイトが完成しそうだから頑張る"

    %button.input{name: "action", type: "submit"} 送信

app/views/posts/edit.html.haml
= render '/header'
= render "form", post: @post

app/views/posts/new.html.haml
= render '/header'
= render "form", post: @post

app/views/posts/show.html.haml
= render '/header'
.post-show
  %h2.post-title
    = icon("fas", "book-open")
    = @post.title
    .post-date
      = @post.learning_date
  - if @post.user.id == current_user.id
    = link_to edit_post_path(@post), class: "post-icon-link" do
      = icon("fas", "pencil-alt", class: "post-edit-icon fa-lg ")
    = link_to post_path(@post), method: :delete, data: { confirm: '削除しますか？' }, class: "post-icon-link" do
      = icon("fas", "trash", class: "post-trash-icon fa-lg")
  .post-contents
    .post-content
      %p.post-content-item
        学習時間
      %p.post-content-time
        = @post.study_time
        %span 時間
      %p.post-content-time
        = @post.study_minutes
        %span 分
    .post-content
      %p.post-content-item
        学習方法
      %p.post-content-text
        = @post.study_method
    .post-content
      %p.post-content-item
        学習内容
      %p.post-content-text
        = @post.content
    .post-content
      %p.post-content-item
        反省点
      %p.post-content-text
        = @post.reflection
    .post-content
      %p.post-content-item
        次回学習内容
      %p.post-content-text
        = @post.next_study
    .post-content
      %p.post-content-item
        その他
      %p.post-content-text
        = @post.other

app/views/relationships/_follow.html.haml
= form_for(current_user.active_relationships.build) do |f|
  %div= hidden_field_tag :following_id, @user.id
  = button_tag type: 'submit', class: "follow-btn" do
    = icon('fa', 'user-plus')
    フォローする

app/views/relationships/_follow_form.html.haml
- if @user != current_user
  .follow_form
    - if current_user.following?(@user)
      = render '/relationships/unfollow'
    - else
      = render '/relationships/follow'

app/views/relationships/_states.html.haml
.states
  = link_to "#{following_user_path(@user)}", class: 'following-link' do
    %strong.following-state
      %span.number
        = @user.following.count
      フォロー
  = link_to "#{followers_user_path(@user)}", class: 'followers-link' do
    %strong.followers-state
      %span.number
        = @user.followers.count
      フォロワー

app/views/relationships/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f|
  = button_tag type: 'submit', class: "follow-btn" do
    フォロー中

app/views/top/index.html.haml
.top-page
  .top-page__logo
    = image_tag 'icon.png', class: 'top-page-icon'
  %h1.top-page__logo-font
    STUDY
    %span.top-page__logo-font--color POST
  %div
    -if user_signed_in?
      = link_to "/users/#{current_user.id}", class: "mypage-link" do
        %span.mypage マイページ
      %div
      = link_to "ログアウト", "/users/sign_out", class: "logout-link"
    -else
      = link_to "ログイン", "/users/sign_in", class: "login-link"
      %div
        = link_to "/users/sign_up", class: "signup-link" do
          %span.signup 新規登録

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
          - current_user.errors.full_messages_for(:name).each do |message|
            .user-validation-error-mesage
              = message
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
          - current_user.errors.full_messages_for(:email).each do |message|
            .user-validation-error-mesage
              = message
        .field
          .field-label
            = f.label :avatar
          .field-input
            = f.file_field :avatar
            = f.hidden_field :avatar_cache
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/index.html.haml
= render '/header'
%h2.search-user 検索結果
.search-user-cards
  - @search_users.each do |user|
    %section.search-user-card
      - if user.avatar.present?
        = image_tag user.avatar.url, class: 'search-user-card-img'
      - else
        = image_tag "no-image.png", class: 'search-user-card-img'
      .search-user-card-content
        %h1.search-user-card-title
          = user.name
      .search-user-card-link
        = link_to '詳細', user_path(user), class: 'user-name-link'

app/views/users/show.html.haml
= render '/header'
.myPage
  .myPage__left-contents
    %h2.myPage-title 学習記録
    .myPage__post-list
      - @posts.each do |post|
        .myPage__post
          .myPage__post-date
            = post.learning_date
          = link_to post_path(post) do
            .myPage__post-title
              = post.title
  .myPage__right-content
    .icon-box
      - if @user.avatar.present?
        = image_tag @user.avatar.url, class: "icon"
      - else
        = image_tag "no-image.png", class: "icon"
    .myPage__user-info
      = @user.name
    %section.stats
      = render '/relationships/states'
    = render '/relationships/follow_form'
    .study_total
      %h4 総学習
      %h4.study_total_value
        = @study_total
      %h4 時間

  :javascript
    calendar_print();

app/views/users/show_follow.html.haml
= render '/header'
%h2.following-user フォロー中
.following-user-cards
  - @user.following.each do |user|
    %section.following-user-card
      - if user.avatar.present?
        = image_tag user.avatar.url, class: 'following-user-card-img'
      - else
        = image_tag "no-image.png", class: 'following-user-card-img'
      .following-user-card-content
        %h1.following-user-card-title
          = user.name
      .following-user-card-link
        = link_to '詳細', user_path(user), class: 'user-name-link'

app/views/users/show_follower.html.haml
= render '/header'
%h2.followers-user フォロワー
.followers-user-cards
  - @user.followers.each do |user|
    %section.followers-user-card
      - if user.avatar.present?
        = image_tag user.avatar.url, class: 'followers-user-card-img'
      - else
        = image_tag "no-image.png", class: 'followers-user-card-img'
      .followers-user-card-content
        %h1.followers-user-card-title
          = user.name
      .followers-user-card-link
        = link_to '詳細', user_path(user), class: 'user-name-link'